test: Setup CI
Fuco1/trinary-logic pull request #3
Opened 2023-02-12 00:53 UTC by jcs090218

Also fixes the URL.

2023-02-12 13:26 UTC, Fuco1 requested changes

2023-02-12 13:26 UTC, Fuco1 commented on Makefile
> +	$(EASK) test ert ./test/*.el
We are using buttercup not ert

2023-02-12 18:53 UTC, jcs090218 commented on Makefile
> +	$(EASK) test ert ./test/*.el
Updated!

2023-02-12 18:54 UTC, jcs090218 commented
I've completely removed Makefile and changed the test from ert to buttercup.

2023-02-13 12:17 UTC, merged

2023-02-13 12:17 UTC, Fuco1 commented
Great, thanks!